class_name GameText
extends RefCounted

const EN := {
	"credits_menu": "CREDITS & DATA", "credits_title": "CREDITS & DATA DISCLOSURE", "credits_overline": "PROJECT INFORMATION",
	"credits_subtitle": "PSYCHIC VECTOR // CURRENT BUILD", "credits_page_count": "%02d / %02d",
	"credits_previous": "PREVIOUS", "credits_next": "NEXT", "credits_close": "RETURN TO TITLE",
	"credits_project_title": "PROJECT & DEVELOPMENT",
	"credits_project_body": "PSYCHIC VECTOR is an original vertical bullet-hell game project.\n\nPRODUCTION, GAME DESIGN & PROGRAMMING\nGame systems, campaign content, interface, production tools, and implementation were created specifically for this project.\n\nENGINE\nBuilt with the Godot Engine. Godot is used for gameplay, rendering, interface, input, audio playback, and local data access.",
	"credits_media_title": "ART & AUDIO PRODUCTION",
	"credits_media_body": "VISUAL PRODUCTION\nOriginal, project-bound raster artwork was created with OpenAI's built-in image-generation tool. Procedural backgrounds, shaders, particles, compositing, and interface treatment are authored in Godot.\n\nAUDIO PRODUCTION\nOriginal music and sound effects are synthesized in memory at runtime from authored themes and sound definitions.\n\nASSET SOURCE NOTES\nFull generation and provenance notes are documented in assets/ART_PROVENANCE.md.",
	"credits_privacy_title": "LOCAL DATA & PRIVACY",
	"credits_privacy_body": "LOCAL STORAGE\nSettings, progression, play records, replay inputs, and a 12-session exit journal are stored in this build's local application-data folder.\n\nSESSION DIAGNOSTICS\nA missing clean-exit marker only infers that a prior session ended abnormally; this is not a native crash dump. Each marker includes the non-player release candidate ID needed to match a report to the exact build. No stack trace, hardware ID, or player identity is collected.\n\nMANUAL JSON EXPORT\nGameplay metrics or session diagnostics are written locally only after the player selects an export in the Combat Archive.\n\nNETWORK\nThis build contains no network transmission or online telemetry. Nothing is uploaded. Formal privacy and legal review remains pending.",
	"risk_reserve_short": "RISK", "risk_bank_bonus": "RISK BANK BONUS",
	"risk_route_hint": "RISK ROUTE // GRAZE TO CHARGE  ·  BOSS GATES BANK  ·  HIT/BARRIER FORFEITS",
	"radio_speaker_command": "VECTOR COMMAND", "radio_speaker_tactical": "TACTICAL RELAY", "radio_speaker_analysis": "FIELD ANALYSIS",
	"radio_neon_gate_open": "VECTOR SYNC IS STABLE. THE DISTRICT GATE IS OPEN.\nKEEP MOVING BEFORE THE NETWORK RECOVERS.",
	"radio_neon_arbiter_inbound": "ARBITER SIGNAL DESCENDING ON THE CONTROL SPINE.\nCLEAR THE LANE BEFORE IT SEALS.",
	"radio_neon_spine_breached": "ARBITER OFFLINE. SERAPH'S CARRIER SIGNAL IS EXPOSED.\nFOLLOW IT DEEPER INTO THE SPINE.",
	"radio_neon_seraph_focus": "SERAPH IS DRAWING THE NETWORK INTO A SINGLE POINT.\nFINAL PSYCHIC SIGNATURE DIRECTLY AHEAD.",
	"radio_tempest_uplink_restored": "UPLINK RESTORED. WIND SHEAR IS MASKING YOUR VECTOR.\nTRUST THE BEACON AND KEEP CLIMBING.",
	"radio_tempest_warden_feed": "ION WARDEN IS FEEDING THE STORM FROM THE ASCENT CORE.\nITS CONTAINMENT FIELD IS CLOSING.",
	"radio_tempest_storm_redirect": "WARDEN OFFLINE. THE STORM DID NOT WEAKEN—\nIT CHANGED COURSE TOWARD THE CITY.",
	"radio_tempest_horizon_fold": "VOID ARCHON CONFIRMED. THE HORIZON IS FOLDING INWARD.\nBREAK THE SIGNAL BEFORE THE FRONT DESCENDS.",
	"radio_forge_orbit_breach": "ORBITAL BREACH CONFIRMED. THE FORGE IS DRAWING POWER FROM THE OPEN SUN.\nSTAY INSIDE THE DARK TRANSIT LANE.",
	"radio_forge_harvester_lock": "CROWN HARVESTER HAS SEALED THE CORE APPROACH.\nBREAK ITS ORBIT BEFORE THE FURNACE ALIGNS.",
	"radio_forge_core_exposed": "HARVESTER DOWN. THE COMMAND SIGNAL IS INSIDE THE ECLIPSE CORE.\nTHE FORGE IS BUILDING A BODY AROUND IT.",
	"radio_forge_eclipse_manifest": "AURELION ZERO HAS MANIFESTED. ALL SOLAR FEEDS ARE CONVERGING.\nEND THE COMMAND NETWORK AT ITS SOURCE.",
	"operation_briefing": "OPERATION BRIEFING", "briefing_situation": "SITUATION", "briefing_objective": "PRIMARY OBJECTIVE",
	"briefing_transmission": "INCOMING TRANSMISSION", "briefing_continue": "CONTINUE TO DEPLOYMENT", "briefing_skip": "SKIP BRIEFING",
	"briefing_cancel_hint": "ESC / B  RETURN TO VECTOR SELECT", "briefing_difficulty": "THREAT PROFILE // %s",
	"neon_briefing_eyebrow": "OPERATION 01 // BREAK THE LOCK",
	"neon_briefing_situation": "SECTOR 07 IS SEALED BY A PSYCHIC COMMAND NETWORK. ARBITER-03 GUARDS THE ONLY APPROACH TO ITS CONTROL SPINE.",
	"neon_briefing_objective": "BREACH THE DISTRICT, DESTROY THE ARBITER, AND SEVER SERAPH'S CONTROL SPINE BEFORE THE LOCKDOWN BECOMES PERMANENT.",
	"neon_briefing_source": "VECTOR COMMAND // RELAY 7",
	"neon_briefing_transmission": "THE CITY IS STILL ANSWERING SERAPH'S ORDERS. CUT THE SIGNAL, AND THE SKY ABOVE THE SPINE SHOULD OPEN.",
	"tempest_briefing_eyebrow": "OPERATION 02 // ASCEND THE NULL FRONT",
	"tempest_briefing_situation": "SERAPH'S COLLAPSE EXPOSED A SECOND COMMAND SIGNAL ABOVE THE CITY. THE SHATTERED ARCOLOGY IS NOW INSIDE A SELF-SUSTAINING PSYCHIC STORM.",
	"tempest_briefing_objective": "ASCEND THROUGH THE TEMPEST, DISCHARGE THE ION WARDEN, AND ERASE THE VOID ARCHON GENERATING THE NULL FRONT.",
	"tempest_briefing_source": "VECTOR COMMAND // OPEN CHANNEL",
	"tempest_briefing_transmission": "THE LOCKDOWN WAS ONLY A CAGE. WHATEVER SERAPH CONTAINED HAS TAKEN CONTROL OF THE STORM. DO NOT LET IT REACH THE CITY.",
	"forge_briefing_eyebrow": "OPERATION 03 // BREAK THE FALSE DAWN",
	"forge_briefing_situation": "THE NULL FRONT'S COLLAPSE EXPOSED AN ORBITAL SOLAR FOUNDRY ABOVE THE STORM. EVERY COMMAND SIGNAL IN THE CITY CONVERGES ON ITS ECLIPSE CORE.",
	"forge_briefing_objective": "BREACH HELIOS FORGE, DISMANTLE THE CROWN HARVESTER, AND DESTROY AURELION ZERO BEFORE THE NETWORK REIGNITES.",
	"forge_briefing_source": "VECTOR COMMAND // FINAL ASCENT",
	"forge_briefing_transmission": "THE STORM WAS A VEIL, NOT THE SOURCE. THE MACHINE ABOVE IT HAS BEEN MANUFACTURING EVERY ORDER WE FOUGHT. THIS IS THE LAST LINK.",
	"campaign_ending": "CAMPAIGN COMPLETE", "ending_epilogue": "VECTOR EPILOGUE", "ending_final_transmission": "FINAL TRANSMISSION",
	"ending_view_results": "VIEW AFTER-ACTION REPORT", "ending_skip_hint": "ESC / B  SKIP TO RESULTS",
	"ending_score_stamp": "FINAL SCORE  %012d  //  CLEAR  %s",
	"tempest_ending_eyebrow": "FINAL OPERATION // NULL FRONT CLOSED",
	"tempest_ending_title": "A SKY WITHOUT ORDERS",
	"tempest_ending_body": "THE VOID ARCHON'S HORIZON COLLAPSES. THE STORM DOES NOT EXPLODE; IT FORGETS HOW TO EXIST. ABOVE THE SHATTERED ARCOLOGY, THE FIRST UNCOMMANDED DAWN IN YEARS REACHES THE CITY BELOW.",
	"tempest_ending_source": "VECTOR COMMAND // LAST OPEN CHANNEL",
	"tempest_ending_transmission": "NO COMMAND SIGNAL. NO LOCKDOWN RESPONSE. THE SKY IS OURS AGAIN.",
	"tempest_ending_kira": "KIRA HOLDS POSITION UNTIL EVERY DISTRICT LIGHT RETURNS. FOR ONCE, HER NEXT VECTOR IS HERS TO CHOOSE.",
	"tempest_ending_dae": "DAE LETS THE LAST GRAVITY FIELD DISSOLVE AROUND HIS HANDS. THE POWER THAT ONCE HELD THE CITY DOWN NOW LIFTS ITS SURVIVORS HOME.",
	"tempest_ending_mina": "MINA RACES THE DAWN ACROSS THE OPEN SKY, MAPPING ROUTES NO COMMAND NETWORK CAN EVER CLOSE AGAIN.",
	"forge_ending_eyebrow": "FINAL OPERATION // FALSE SUN EXTINGUISHED",
	"forge_ending_title": "A DAWN THAT BELONGS TO NO ONE",
	"forge_ending_body": "AURELION ZERO FRACTURES, AND THE ORBITAL FORGE RELEASES ITS HOLD ON THE SUN. ACROSS THE CITY, COMMAND RELAYS FALL SILENT ONE BY ONE. THE LIGHT THAT REACHES THE STREETS CARRIES NO ORDER—ONLY MORNING.",
	"forge_ending_source": "VECTOR COMMAND // FIRST FREE CHANNEL",
	"forge_ending_transmission": "THE NETWORK IS GONE. NO CARRIER, NO CAGE, NO VOICE ABOVE OURS. COME HOME WHEN YOU ARE READY.",
	"forge_ending_kira": "KIRA TRACES THE LAST FALLING SPARK UNTIL IT BECOMES AN ORDINARY STAR. HER NEXT VECTOR BEGINS WITHOUT A TARGET ASSIGNED.",
	"forge_ending_dae": "DAE TURNS THE FORGE'S DEAD GRAVITY RINGS INTO AN EVACUATION BRIDGE. FOR THE FIRST TIME, HIS STRENGTH MOVES PEOPLE BY THEIR CHOICE.",
	"forge_ending_mina": "MINA CROSSES THE UNGUARDED ORBIT BEFORE THE SUN CLEARS THE HORIZON, LEAVING THE FIRST ROUTE MARKED SIMPLY: OPEN.",
	"start_game": "START GAME", "boss_practice": "BOSS PRACTICE", "combat_archive": "COMBAT ARCHIVE", "options": "OPTIONS", "how_to_play": "HOW TO PLAY", "quit": "QUIT",
	"select_operation_route": "SELECT OPERATION ROUTE", "campaign_network": "CAMPAIGN NETWORK // DEPLOYMENT CONTROL",
	"no_routes_available": "NO ROUTES AVAILABLE", "routes_online": "ROUTES ONLINE", "catalog_offline": "CATALOG OFFLINE",
	"stage_label": "STAGE", "locked": "LOCKED", "route_time": "ROUTE TIME", "difficulty_label": "DIFFICULTY",
	"route_ready": "ROUTE CLEARED FOR DEPLOYMENT", "route_unlock_previous": "CLEAR THE PREVIOUS ROUTE TO UNLOCK",
	"route_access_denied": "ACCESS DENIED // ROUTE LOCKED", "select_route": "SELECT ROUTE",
	"archive_sub": "AFTER-ACTION ANALYTICS // 60 RUNS + 12 REPLAYS",
	"archive_runs": "RUNS", "archive_clears": "CLEARS", "clear_rate": "CLEAR RATE",
	"average_losses": "AVG LOSSES", "average_barriers": "AVG BARRIERS", "best_clear": "BEST CLEAR",
	"best_score": "BEST SCORE", "overdrive_rate": "OVERDRIVE RATE", "recent_runs": "RECENT RUNS",
	"vector_breakdown": "VECTOR BREAKDOWN",
	"no_run_data": "NO CAMPAIGN DATA FOR THIS DIFFICULTY", "export_data": "EXPORT PLAYTEST JSON", "export_diagnostics": "EXPORT DIAGNOSTICS",
	"export_success": "JSON SAVED TO THE USER DATA FOLDER", "diagnostics_export_success": "DIAGNOSTICS SAVED LOCALLY", "export_failed": "EXPORT FAILED",
	"diagnostics_unclean_notice": "PRIOR SESSION ENDED WITHOUT A CLEAN-EXIT MARKER", "diagnostics_reset_notice": "CORRUPT SESSION JOURNAL WAS SAFELY RESET",
	"archive_back": "BACK TO TITLE", "cleared_short": "CLEAR", "failed_short": "LOST", "assisted_short": "ASSIST",
	"watch_replay": "WATCH LAST REPLAY", "next_operation": "NEXT OPERATION", "replay_mode": "REPLAY", "replay_sub": "LAST RUN // INPUT PLAYBACK",
	"watch_selected_replay": "WATCH REPLAY %02d/%02d", "replay_vault": "REPLAY VAULT",
	"replay_empty": "NO SAVED REPLAYS", "replay_pinned": "PINNED", "replay_incompatible": "INCOMPATIBLE",
	"replay_verified": "REPLAY VERIFIED // RESULTS MATCH", "replay_desync": "REPLAY DESYNC // RESULTS DIFFER",
	"replay_unavailable": "NO COMPATIBLE REPLAY AVAILABLE", "replay_invalid": "REPLAY ENDED // INCOMPLETE OR INCOMPATIBLE DATA",
	"practice_select": "SELECT PRACTICE VECTOR", "practice_sub": "SERAPH EXECUTOR // CHOOSE A START PHASE",
	"practice_sub_stage": "%s // CHOOSE A START PHASE",
	"practice_phase_hint": "UP / DOWN  START PHASE %02d // %s",
	"difficulty_hint": "UP / DOWN  %s // %s",
	"difficulty_story": "STORY", "difficulty_story_desc": "5 LIVES / 78% THREAT",
	"difficulty_normal": "NORMAL", "difficulty_normal_desc": "3 LIVES / ORIGINAL BALANCE",
	"difficulty_expert": "EXPERT", "difficulty_expert_desc": "2 LIVES / 118% THREAT",
	"briefing_title": "COMBAT BRIEFING",
	"start_training": "PLAY INTERACTIVE TRAINING",
	"training_title": "VECTOR CALIBRATION", "training_sub": "LIVE CONTROL TUTORIAL // INPUTS USE YOUR CURRENT BINDINGS",
	"training_skip": "SKIP TRAINING", "training_deploy": "CALIBRATION COMPLETE",
	"training_move": "01 // MANEUVER", "training_primary": "02 // PRIMARY SHOT",
	"training_focus": "03 // FOCUS ATTACK", "training_barrier": "04 // PSYCHIC BARRIER",
	"training_complete": "VECTOR SYNCHRONIZED",
	"training_move_desc": "%s %s %s %s / ARROWS / LEFT STICK\nTRAVEL THROUGH THE CALIBRATION FIELD",
	"training_primary_desc": "HOLD %s / %s TO FIRE\nWIDE SUSTAINED ATTACK FOR ROUTE ENEMIES",
	"training_focus_desc": "HOLD %s / %s FOR FOCUS\nPRECISE MOVEMENT AND CONCENTRATED DAMAGE",
	"training_barrier_desc": "PRESS %s / %s NOW\nERASE THE ENCLOSING BULLETS",
	"training_complete_desc": "MOVEMENT, ATTACK, AND DEFENSE VERIFIED\nTHE NEON DISTRICT IS READY",
	"training_target": "HOLOGRAPHIC TARGET", "training_progress": "CALIBRATION %03d%%",
	"training_hold": "PERFORM THE HIGHLIGHTED ACTION", "training_complete_hint": "CONFIRM TO CONTINUE TO VECTOR SELECTION",
	"briefing_body": "REACH THE CONTROL SPINE AND DESTROY SERAPH.\n\nPRIMARY SHOT — sustained wide attack\nFOCUS ATTACK — slower precision movement and concentrated fire\nPSYCHIC BARRIER — clears nearby bullets; refills to 3 after a lost life\n\nRISK RESERVE — graze to charge it; boss gates bank it for score. A hit or barrier forfeits the current reserve.\n\nGRADE 3 — fast straight triple burst\nGRADE 2 — medium-speed radial attack\nGRADE 1 — slow circular attack, fired three times\n\nTHE MIDBOSS PAUSES THE THREE-MINUTE ROUTE CLOCK.\nTHE FINAL BOSS ARRIVES AT 03:00 OF ROUTE TIME.",
	"system_options": "SYSTEM OPTIONS", "master": "MASTER", "music": "MUSIC", "sfx": "SFX",
	"screen_shake": "SCREEN SHAKE", "flash": "FLASH", "bullet_contrast": "BULLET CONTRAST",
	"auto_fire": "AUTO PRIMARY FIRE", "auto_barrier": "AUTO BARRIER INTERCEPT", "show_hitbox": "ALWAYS SHOW HITBOX",
	"fullscreen": "FULLSCREEN", "language": "LANGUAGE: ENGLISH", "accessibility_assists": "ACCESSIBILITY & ASSISTS",
	"assist_preset": "ASSIST PRESET", "assist_standard": "STANDARD", "assist_comfort": "COMFORT", "assist_guardian": "GUARDIAN", "assist_custom": "CUSTOM",
	"assist_standard_desc": "Original presentation and manual defense.",
	"assist_comfort_desc": "Reduced motion and flashes, clear bullets, auto fire, and visible hitbox.",
	"assist_guardian_desc": "Comfort settings plus automatic barrier interception.",
	"assist_custom_desc": "Custom accessibility configuration.",
	"assist_ranking_note": "AUTO BARRIER MARKS THE RUN AS ASSISTED AND DISABLES RECORD SUBMISSION.",
	"assist_active": "ASSIST ACTIVE", "assisted_report": "ASSISTED RUN // RECORD DISABLED",
	"auto_barrier_trigger": "AUTO BARRIER", "auto_barrier_sub": "DAMAGE INTERCEPTED // RECORD DISABLED",
	"key_bindings": "KEY BINDINGS", "back": "BACK", "back_options": "BACK TO OPTIONS",
	"binding_device": "%s BINDINGS", "device_keyboard": "KEYBOARD", "device_gamepad": "GAMEPAD",
	"reset_keys": "RESET DEFAULT KEYS", "reset_gamepad": "RESET GAMEPAD BUTTONS", "press_key": "PRESS A KEY", "press_button": "PRESS A BUTTON",
	"binding_hint": "SELECT AN ACTION, THEN PRESS A KEY\nESC CANCELS // CONTROLLER INPUTS STAY ACTIVE",
	"gamepad_binding_hint": "SELECT AN ACTION, THEN PRESS A GAMEPAD BUTTON\nESC CANCELS // MOVEMENT STAYS ON STICK / D-PAD",
	"gamepad_connected": "%d GAMEPAD CONNECTED", "gamepad_disconnected": "NO GAMEPAD // SETTINGS APPLY ON CONNECTION",
	"controller_connected": "GAMEPAD CONNECTED", "controller_disconnected": "GAMEPAD DISCONNECTED // KEYBOARD ACTIVE",
	"save_recovered": "SAVE RECOVERED // LAST VALID BACKUP RESTORED",
	"controls_hint": "MOVE  %s / ARROWS / STICK\nSHOT  %s / %s   FOCUS  %s / %s\nBARRIER  %s / %s   PAUSE  ESC / START",
	"move_up": "MOVE UP", "move_down": "MOVE DOWN", "move_left": "MOVE LEFT", "move_right": "MOVE RIGHT",
	"primary": "PRIMARY SHOT", "focus": "FOCUS ATTACK", "barrier": "PSYCHIC BARRIER",
	"select_vector": "SELECT YOUR VECTOR", "select_sub": "ESCAPED SUBJECT // COMBAT LOADOUT",
	"focus_desc": "FOCUS: precision movement + concentrated psychic channel",
	"select": "SELECT", "deploy": "DEPLOY", "speed": "SPEED", "power": "POWER", "width": "WIDTH",
	"character_a_role": "VECTOR BALANCE", "character_a_shot": "TRI-VECTOR",
	"character_a_desc": "Stable spread / adaptive focus",
	"character_b_role": "GRAVITY POWER", "character_b_shot": "CRUSH LANCE",
	"character_b_desc": "Narrow field / maximum impact",
	"character_c_role": "PHASE SPEED", "character_c_shot": "PHASE FAN",
	"character_c_desc": "Wide coverage / rapid movement",
	"vector_suspended": "VECTOR SUSPENDED", "pause_sub": "PAUSE // NEON DISTRICT",
	"resume": "RESUME", "restart_stage": "RESTART STAGE", "audio": "AUDIO: %d%%", "quit_title": "QUIT TO TITLE",
	"retry": "RETRY", "return_title": "RETURN TO TITLE", "mission_complete": "MISSION COMPLETE",
	"practice_complete": "PRACTICE COMPLETE", "practice_report": "SERAPH // TRAINING ANALYSIS", "practice_report_stage": "%s // TRAINING ANALYSIS",
	"vector_lost": "VECTOR LOST", "after_action": "NEON DISTRICT // AFTER-ACTION REPORT",
	"combat_score": "COMBAT SCORE", "enemies_destroyed": "ENEMIES DESTROYED", "graze": "GRAZE",
	"max_chain": "MAX CHAIN", "vector_losses": "VECTOR LOSSES", "barriers_used": "BARRIERS USED",
	"clear_time": "CLEAR TIME", "phase_bonus": "PHASE BONUS", "total_score": "TOTAL SCORE",
	"performance_medals": "PERFORMANCE MEDALS", "medal_bonus": "MEDAL BONUS",
	"medal_no_miss": "UNTOUCHED VECTOR", "medal_no_miss_desc": "Clear without losing a life.",
	"medal_no_barrier": "SEALED ARSENAL", "medal_no_barrier_desc": "Clear without activating a Psychic Barrier.",
	"medal_phase_perfect": "PHASE AUTHORITY", "medal_phase_perfect_desc": "Clear every boss phase before Overdrive.",
	"new_high_score": "NEW HIGH SCORE", "score": "SCORE", "high_score": "HIGH SCORE",
	"vector": "VECTOR", "chain": "CHAIN", "phase": "PHASE", "overdrive": "OVERDRIVE",
	"stage_title": "NEON DISTRICT", "stage_sub": "SECTOR 07 // CONTROL SPINE APPROACH",
	"boss_arbiter_name": "ARBITER-03", "boss_seraph_name": "SERAPH EXECUTOR",
	"null_tempest_title": "NULL TEMPEST", "null_tempest_subtitle": "SHATTERED ARCOLOGY // STORM ASCENT",
	"null_tempest_result": "NULL TEMPEST // AFTER-ACTION REPORT", "null_tempest_pause": "PAUSE // NULL TEMPEST",
	"boss_ion_warden_name": "ION WARDEN", "boss_ion_warden_subtitle": "ATMOSPHERIC CONTAINMENT ENGINE",
	"boss_ion_warden_defeat_title": "WARDEN DISCHARGED", "boss_ion_warden_defeat_subtitle": "ASCENT CORRIDOR RESTORED",
	"boss_void_archon_name": "VOID ARCHON", "boss_void_archon_subtitle": "HORIZON-CLASS PSYCHIC ANOMALY",
	"boss_void_archon_defeat_title": "HORIZON COLLAPSED", "boss_void_archon_defeat_subtitle": "THE TEMPEST IS BREAKING",
	"helios_forge_title": "HELIOS FORGE", "helios_forge_subtitle": "ORBITAL FOUNDRY // ECLIPSE CORE",
	"helios_forge_result": "HELIOS FORGE // AFTER-ACTION REPORT", "helios_forge_pause": "PAUSE // HELIOS FORGE",
	"boss_crown_harvester_name": "CROWN HARVESTER", "boss_crown_harvester_subtitle": "ORBITAL SOLAR REAPER",
	"boss_crown_harvester_defeat_title": "CROWN DISMANTLED", "boss_crown_harvester_defeat_subtitle": "ECLIPSE CORE EXPOSED",
	"boss_aurelion_zero_name": "AURELION ZERO", "boss_aurelion_zero_subtitle": "COMMAND-SUN PROGENITOR",
	"boss_aurelion_zero_defeat_title": "FALSE SUN EXTINGUISHED", "boss_aurelion_zero_defeat_subtitle": "THE COMMAND NETWORK IS SILENT",
	"hostile_surge": "HOSTILE SURGE", "chain_window": "CHAIN WINDOW EXTENDED",
	"environment_hazard": "ENVIRONMENT HAZARD", "evasive_action": "EVASIVE ACTION REQUIRED",
	"final_boss_sub": "PSYCHIC WEAPON // THREAT OMEGA", "midboss_sub": "AERIAL VERDICT PLATFORM",
	"arbiter_down": "ARBITER DOWN", "advance_spine": "ADVANCE TO CENTRAL SPINE",
	"control_severed": "CONTROL SPINE SEVERED", "lockdown_collapsing": "CITY LOCKDOWN COLLAPSING",
	"vector_disrupted": "VECTOR DISRUPTED", "life_signal": "LIFE SIGNAL %d", "power_up": "POWER UP",
	"warning": "WARNING", "psychic_signal": "HIGH-ORDER PSYCHIC SIGNAL",
	"signature_confirmed": "PSYCHIC SIGNATURE CONFIRMED",
	"boss_phase_perimeter": "PERIMETER DENIAL", "boss_phase_rotary": "ROTARY JUDGEMENT",
	"boss_phase_arbiter": "ARBITER OVERDRIVE", "boss_phase_sentence": "VECTOR SENTENCE",
	"boss_phase_halo": "HALO ENGINE", "boss_phase_maelstrom": "SYNAPTIC MAELSTROM",
	"boss_phase_lattice": "LATTICE OF NULL", "boss_phase_last_light": "LAST LIGHT PROTOCOL",
	"boss_phase_static_verdict": "STATIC VERDICT", "boss_phase_ion_shear": "ION SHEAR",
	"boss_phase_thunder_cage": "THUNDER CAGE", "boss_phase_eye_of_storm": "EYE OF THE STORM",
	"boss_phase_violet_front": "VIOLET FRONT", "boss_phase_chain_lightning": "CHAIN LIGHTNING",
	"boss_phase_broken_sky": "BROKEN SKY", "boss_phase_zero_horizon": "ZERO HORIZON",
	"boss_phase_reaping_orbit": "REAPING ORBIT", "boss_phase_crown_arc": "CROWN ARC",
	"boss_phase_furnace_lock": "FURNACE LOCK", "boss_phase_first_ignition": "FIRST IGNITION",
	"boss_phase_photosphere_crown": "PHOTOSPHERE CROWN", "boss_phase_prominence_lances": "PROMINENCE LANCES",
	"boss_phase_blackbody_dominion": "BLACKBODY DOMINION", "boss_phase_last_dawn": "LAST DAWN PROTOCOL"
}

const KO := {
	"credits_menu": "크레딧 및 데이터", "credits_title": "크레딧 및 데이터 안내", "credits_overline": "프로젝트 정보",
	"credits_subtitle": "PSYCHIC VECTOR // 현재 빌드", "credits_page_count": "%02d / %02d",
	"credits_previous": "이전", "credits_next": "다음", "credits_close": "타이틀로 돌아가기",
	"credits_project_title": "프로젝트 및 개발",
	"credits_project_body": "PSYCHIC VECTOR는 오리지널 세로형 탄막 슈팅 게임 프로젝트입니다.\n\n제작·게임 디자인·프로그래밍\n게임 시스템, 캠페인 콘텐츠, 인터페이스, 제작 도구와 구현은 이 프로젝트를 위해 제작됐습니다.\n\n엔진\nGodot Engine으로 제작했습니다. Godot은 게임플레이, 렌더링, 인터페이스, 입력, 오디오 재생과 로컬 데이터 접근에 사용됩니다.",
	"credits_media_title": "아트 및 오디오 제작",
	"credits_media_body": "비주얼 제작\n프로젝트 전용 오리지널 래스터 아트는 OpenAI 내장 이미지 생성 도구로 제작했습니다. 절차적 배경, 셰이더, 파티클, 합성과 인터페이스 연출은 Godot에서 제작했습니다.\n\n오디오 제작\n오리지널 음악과 효과음은 제작된 테마와 사운드 정의를 바탕으로 런타임에 메모리에서 합성됩니다.\n\n에셋 출처 안내\n전체 생성 과정과 출처 기록은 assets/ART_PROVENANCE.md에 문서화되어 있습니다.",
	"credits_privacy_title": "로컬 데이터 및 개인정보",
	"credits_privacy_body": "로컬 저장\n설정, 진행 상태, 플레이 기록, 리플레이 입력과 최근 12개 세션의 종료 저널은 로컬 앱 데이터 폴더에 저장됩니다.\n\n세션 진단\n정상 종료 표시가 없을 때만 이전 세션의 비정상 종료를 추정하며, 이는 네이티브 크래시 덤프가 아닙니다. 각 표시는 보고서를 정확한 빌드와 연결하기 위한 비개인 릴리스 후보 ID만 포함합니다. 스택 추적, 하드웨어 ID, 플레이어 신원을 수집하지 않습니다.\n\n수동 JSON 내보내기\n전투 지표와 세션 진단은 전투 기록에서 플레이어가 각 내보내기를 선택할 때만 로컬 파일로 작성됩니다.\n\n네트워크\n이 빌드에는 네트워크 전송과 온라인 텔레메트리가 없으며 아무것도 업로드되지 않습니다. 정식 개인정보 및 법률 검토는 아직 완료되지 않았습니다.",
	"risk_reserve_short": "리스크", "risk_bank_bonus": "리스크 비축 보너스",
	"risk_route_hint": "리스크 루트 // 스치기로 충전  ·  보스 진입 시 확정  ·  피격/배리어 사용 시 손실",
	"radio_speaker_command": "벡터 사령부", "radio_speaker_tactical": "전술 중계", "radio_speaker_analysis": "현장 분석",
	"radio_neon_gate_open": "벡터 동기화 안정. 구역 진입문이 열렸다.\n명령망이 복구되기 전에 계속 전진하라.",
	"radio_neon_arbiter_inbound": "아비터 신호가 통제 중추로 하강 중이다.\n진입로가 봉쇄되기 전에 돌파하라.",
	"radio_neon_spine_breached": "아비터 정지. 세라프의 반송 신호가 노출됐다.\n신호를 따라 통제 중추 안쪽으로 진입하라.",
	"radio_neon_seraph_focus": "세라프가 명령망을 한 점으로 집중시키고 있다.\n최종 사이킥 신호가 바로 앞이다.",
	"radio_tempest_uplink_restored": "업링크 복구. 풍력 전단이 벡터를 가리고 있다.\n비콘을 믿고 계속 상승하라.",
	"radio_tempest_warden_feed": "이온 워든이 상승로 코어에서 폭풍을 증폭 중이다.\n대기권 봉쇄망이 좁혀지고 있다.",
	"radio_tempest_storm_redirect": "워든 정지. 폭풍은 약해지지 않았다.\n방향을 바꿔 도시로 향하고 있다.",
	"radio_tempest_horizon_fold": "보이드 아콘 확인. 지평선이 안으로 접히고 있다.\n전선이 하강하기 전에 신호를 끊어라.",
	"radio_forge_orbit_breach": "궤도 돌입 확인. 포지가 열린 태양에서 동력을 흡수하고 있다.\n어두운 수송로 안쪽을 유지하라.",
	"radio_forge_harvester_lock": "크라운 하베스터가 코어 접근로를 봉쇄했다.\n용광로가 정렬되기 전에 궤도를 파괴하라.",
	"radio_forge_core_exposed": "하베스터 격파. 명령 신호는 이클립스 코어 내부에 있다.\n포지가 신호 주변에 육체를 만들고 있다.",
	"radio_forge_eclipse_manifest": "아우렐리온 제로 출현. 모든 태양 동력이 집결 중이다.\n명령망의 근원을 끝내라.",
	"operation_briefing": "작전 브리핑", "briefing_situation": "작전 상황", "briefing_objective": "최우선 목표",
	"briefing_transmission": "수신 전송", "briefing_continue": "출격으로 이동", "briefing_skip": "브리핑 건너뛰기",
	"briefing_cancel_hint": "ESC / B  벡터 선택으로", "briefing_difficulty": "위협 등급 // %s",
	"neon_briefing_eyebrow": "작전 01 // 봉쇄를 부수라",
	"neon_briefing_situation": "07 구역은 사이킥 명령망에 의해 봉쇄되어 있다. 아비터-03이 통제 중추로 향하는 유일한 진입로를 지키고 있다.",
	"neon_briefing_objective": "구역을 돌파하고 아비터를 격파한 다음, 봉쇄가 영구히 고정되기 전에 세라프의 통제 중추를 절단하라.",
	"neon_briefing_source": "벡터 사령부 // 중계소 7",
	"neon_briefing_transmission": "도시는 아직 세라프의 명령에 응답하고 있다. 신호를 끊으면 통제 중추 위의 하늘이 열릴 것이다.",
	"tempest_briefing_eyebrow": "작전 02 // 널 전선으로 상승하라",
	"tempest_briefing_situation": "세라프가 붕괴하자 도시 상공의 제2 명령 신호가 드러났다. 붕괴된 공중 도시는 자기 지속형 사이킥 폭풍에 갇혀 있다.",
	"tempest_briefing_objective": "폭풍을 뚫고 상승해 이온 워든을 무력화한 다음, 널 전선을 유지하는 보이드 아콘을 소거하라.",
	"tempest_briefing_source": "벡터 사령부 // 개방 채널",
	"tempest_briefing_transmission": "봉쇄는 감옥일 뿐이었다. 세라프가 가두어 왔던 무언가가 폭풍의 지배권을 가져갔다. 도시에 닿기 전에 끝내라.",
	"forge_briefing_eyebrow": "작전 03 // 거짓 새벽을 파괴하라",
	"forge_briefing_situation": "널 전선이 붕괴하자 폭풍 위의 궤도 태양 주조소가 드러났다. 도시의 모든 명령 신호는 그 이클립스 코어로 수렴한다.",
	"forge_briefing_objective": "헬리오스 포지에 돌입해 크라운 하베스터를 해체하고, 명령망이 재점화되기 전에 아우렐리온 제로를 파괴하라.",
	"forge_briefing_source": "벡터 사령부 // 최종 상승로",
	"forge_briefing_transmission": "폭풍은 근원이 아니라 장막이었다. 그 위의 기계가 우리가 싸워 온 모든 명령을 생산했다. 이것이 마지막 연결이다.",
	"campaign_ending": "캠페인 완료", "ending_epilogue": "벡터 에필로그", "ending_final_transmission": "최종 전송",
	"ending_view_results": "전투 결과 보기", "ending_skip_hint": "ESC / B  결과로 건너뛰기",
	"ending_score_stamp": "최종 점수  %012d  //  클리어  %s",
	"tempest_ending_eyebrow": "최종 작전 // 널 전선 폐쇄",
	"tempest_ending_title": "명령 없는 하늘",
	"tempest_ending_body": "보이드 아콘의 지평선이 붕괴한다. 폭풍은 폭발하지 않고, 스스로 존재하는 방법을 잊는다. 붕괴된 공중 도시 너머로, 몇 해 만의 첫 자유로운 새벽빛이 아래의 도시에 닿는다.",
	"tempest_ending_source": "벡터 사령부 // 마지막 개방 채널",
	"tempest_ending_transmission": "명령 신호 없음. 봉쇄 응답 없음. 하늘은 다시 우리 것이다.",
	"tempest_ending_kira": "키라는 모든 구역의 불빛이 돌아올 때까지 자리를 지킨다. 처음으로, 그녀의 다음 벡터는 스스로 선택할 수 있다.",
	"tempest_ending_dae": "대는 손에 머물던 마지막 중력장을 흘려보낸다. 도시를 누르던 힘은 이제 생존자들을 집으로 들어 올린다.",
	"tempest_ending_mina": "미나는 트인 하늘에서 새벽과 경주하며, 어떤 명령망도 다시는 닫을 수 없는 항로를 그려 나간다.",
	"forge_ending_eyebrow": "최종 작전 // 거짓 태양 소멸",
	"forge_ending_title": "누구의 것도 아닌 새벽",
	"forge_ending_body": "아우렐리온 제로가 산산이 부서지고 궤도 포지는 태양을 놓아준다. 도시 전역의 명령 중계기가 하나씩 침묵한다. 거리로 닿는 빛에는 어떤 명령도 없다. 오직 아침만이 남는다.",
	"forge_ending_source": "벡터 사령부 // 최초의 자유 채널",
	"forge_ending_transmission": "명령망은 사라졌다. 반송파도, 감옥도, 우리 위의 목소리도 없다. 준비되면 돌아오라.",
	"forge_ending_kira": "키라는 마지막 불꽃이 평범한 별이 될 때까지 궤적을 좇는다. 그녀의 다음 벡터는 지정된 목표 없이 시작된다.",
	"forge_ending_dae": "대는 멈춘 포지의 중력 고리를 대피 교량으로 바꾼다. 처음으로 그의 힘은 사람들을 그들 자신의 선택에 따라 움직인다.",
	"forge_ending_mina": "미나는 태양이 지평선을 넘기 전에 무방비가 된 궤도를 가로지르며, 첫 항로에 단 하나의 표시를 남긴다. 개방.",
	"start_game": "게임 시작", "boss_practice": "보스 연습", "combat_archive": "전투 기록", "options": "옵션", "how_to_play": "플레이 방법", "quit": "종료",
	"select_operation_route": "작전 경로 선택", "campaign_network": "캠페인 네트워크 // 출격 관제",
	"no_routes_available": "사용 가능한 경로 없음", "routes_online": "활성 경로", "catalog_offline": "카탈로그 오프라인",
	"stage_label": "스테이지", "locked": "잠김", "route_time": "경로 시간", "difficulty_label": "난이도",
	"route_ready": "출격 가능한 경로입니다", "route_unlock_previous": "이전 경로를 클리어하면 해금됩니다",
	"route_access_denied": "접근 거부 // 경로 잠김", "select_route": "경로 선택",
	"archive_sub": "전투 분석 // 최근 기록 60회 + 리플레이 12개",
	"archive_runs": "플레이", "archive_clears": "클리어", "clear_rate": "클리어율",
	"average_losses": "평균 손실", "average_barriers": "평균 배리어", "best_clear": "최고 클리어",
	"best_score": "최고 점수", "overdrive_rate": "오버드라이브율", "recent_runs": "최근 플레이",
	"vector_breakdown": "벡터별 분석",
	"no_run_data": "이 난이도의 캠페인 기록이 없습니다", "export_data": "플레이테스트 JSON 내보내기", "export_diagnostics": "진단 JSON 내보내기",
	"export_success": "JSON을 사용자 데이터 폴더에 저장했습니다", "diagnostics_export_success": "진단 JSON을 로컬에 저장했습니다", "export_failed": "내보내기 실패",
	"diagnostics_unclean_notice": "이전 세션에 정상 종료 표시가 없습니다", "diagnostics_reset_notice": "손상된 세션 저널을 안전하게 초기화했습니다",
	"archive_back": "타이틀로", "cleared_short": "클리어", "failed_short": "실패", "assisted_short": "어시스트",
	"watch_replay": "마지막 플레이 리플레이", "next_operation": "다음 작전", "replay_mode": "리플레이", "replay_sub": "마지막 플레이 // 입력 재생",
	"watch_selected_replay": "리플레이 %02d/%02d 재생", "replay_vault": "리플레이 보관함",
	"replay_empty": "저장된 리플레이가 없습니다", "replay_pinned": "고정", "replay_incompatible": "호환 불가",
	"replay_verified": "리플레이 검증 완료 // 결과 일치", "replay_desync": "리플레이 불일치 // 결과 차이",
	"replay_unavailable": "재생 가능한 리플레이가 없습니다", "replay_invalid": "리플레이 종료 // 불완전하거나 호환되지 않는 데이터",
	"practice_select": "연습용 벡터 선택", "practice_sub": "세라프 집행자 // 시작 페이즈 선택",
	"practice_sub_stage": "%s // 시작 페이즈 선택",
	"practice_phase_hint": "위 / 아래  시작 페이즈 %02d // %s",
	"difficulty_hint": "위 / 아래  %s // %s",
	"difficulty_story": "스토리", "difficulty_story_desc": "목숨 5 / 위협도 78%",
	"difficulty_normal": "노멀", "difficulty_normal_desc": "목숨 3 / 기존 밸런스",
	"difficulty_expert": "익스퍼트", "difficulty_expert_desc": "목숨 2 / 위협도 118%",
	"briefing_title": "전투 브리핑",
	"start_training": "실전 조작 훈련",
	"training_title": "벡터 동기화 훈련", "training_sub": "실전 조작 튜토리얼 // 현재 키 설정 사용",
	"training_skip": "훈련 건너뛰기", "training_deploy": "동기화 완료",
	"training_move": "01 // 기동", "training_primary": "02 // 약공격",
	"training_focus": "03 // 강공격", "training_barrier": "04 // 사이킥 배리어",
	"training_complete": "벡터 동기화 완료",
	"training_move_desc": "%s %s %s %s / 방향키 / 왼쪽 스틱\n훈련 공간을 이동하세요",
	"training_primary_desc": "%s / %s 눌러 발사\n일반 적을 위한 넓은 지속 공격",
	"training_focus_desc": "%s / %s 눌러 집중\n정밀 이동과 집중 화력",
	"training_barrier_desc": "%s / %s 지금 입력\n주변을 조여오는 탄환을 제거하세요",
	"training_complete_desc": "이동·공격·방어 검증 완료\n네온 지구 출격 준비 완료",
	"training_target": "홀로그램 표적", "training_progress": "동기화 %03d%%",
	"training_hold": "표시된 동작을 수행하세요", "training_complete_hint": "확인하면 벡터 선택으로 이동합니다",
	"briefing_body": "통제 중추에 도달해 세라프를 파괴하십시오.\n\n약공격 — 넓은 범위를 지속 공격\n강공격 — 느린 정밀 이동과 집중 사격\n사이킥 배리어 — 주변 탄환 제거, 목숨을 잃으면 3개로 충전\n\n리스크 비축 — 스치기로 충전하며 보스 진입 때 점수로 확정됩니다. 피격 또는 배리어 사용 시 현재 비축량을 잃습니다.\n\n3등급 — 빠른 직선 3점사\n2등급 — 중속 방사형 공격\n1등급 — 느린 원형 공격을 3회 연속 발사\n\n중간보스 전투 중에는 3분 경로 타이머가 멈춥니다.\n최종 보스는 경로 시간 03:00에 등장합니다.",
	"system_options": "시스템 옵션", "master": "전체 음량", "music": "음악", "sfx": "효과음",
	"screen_shake": "화면 흔들림", "flash": "섬광 효과", "bullet_contrast": "적탄 대비",
	"auto_fire": "약공격 자동 발사", "auto_barrier": "배리어 자동 방어", "show_hitbox": "피격점 항상 표시",
	"fullscreen": "전체 화면", "language": "언어: 한국어", "accessibility_assists": "접근성 및 어시스트",
	"assist_preset": "어시스트 프리셋", "assist_standard": "표준", "assist_comfort": "컴포트", "assist_guardian": "가디언", "assist_custom": "사용자 설정",
	"assist_standard_desc": "기존 연출과 수동 방어를 사용합니다.",
	"assist_comfort_desc": "흔들림과 섬광을 줄이고 적탄·자동 사격·피격점 표시를 강화합니다.",
	"assist_guardian_desc": "컴포트 설정에 배리어 자동 방어를 추가합니다.",
	"assist_custom_desc": "사용자가 조정한 접근성 설정입니다.",
	"assist_ranking_note": "배리어 자동 방어를 사용하면 어시스트 플레이로 표시되며 기록이 등록되지 않습니다.",
	"assist_active": "어시스트 활성", "assisted_report": "어시스트 플레이 // 기록 등록 안 됨",
	"auto_barrier_trigger": "배리어 자동 방어", "auto_barrier_sub": "피격 차단 // 기록 등록 안 됨",
	"key_bindings": "키 설정", "back": "뒤로", "back_options": "옵션으로 돌아가기",
	"binding_device": "%s 설정", "device_keyboard": "키보드", "device_gamepad": "게임패드",
	"reset_keys": "기본 키로 초기화", "reset_gamepad": "게임패드 버튼 초기화", "press_key": "키를 입력하세요", "press_button": "버튼을 입력하세요",
	"binding_hint": "동작을 선택한 뒤 키를 누르세요\nESC 취소 // 컨트롤러 입력은 유지됩니다",
	"gamepad_binding_hint": "동작을 선택한 뒤 게임패드 버튼을 누르세요\nESC 취소 // 이동은 스틱과 방향 패드 유지",
	"gamepad_connected": "게임패드 %d개 연결됨", "gamepad_disconnected": "게임패드 없음 // 연결 시 설정 적용",
	"controller_connected": "게임패드 연결됨", "controller_disconnected": "게임패드 연결 해제 // 키보드 사용 가능",
	"save_recovered": "저장 데이터 복구 // 마지막 정상 백업 복원",
	"controls_hint": "이동  %s / 방향키 / 스틱\n약공격  %s / %s   강공격  %s / %s\n배리어  %s / %s   일시정지  ESC / START",
	"move_up": "위로 이동", "move_down": "아래로 이동", "move_left": "왼쪽 이동", "move_right": "오른쪽 이동",
	"primary": "약공격", "focus": "강공격", "barrier": "사이킥 배리어",
	"select_vector": "벡터 선택", "select_sub": "탈주 실험체 // 전투 장비",
	"focus_desc": "집중: 정밀 이동 + 사이킥 집중 사격",
	"select": "선택", "deploy": "출격", "speed": "속도", "power": "화력", "width": "범위",
	"character_a_role": "균형형 벡터", "character_a_shot": "트라이 벡터",
	"character_a_desc": "안정적인 확산 / 적응형 집중",
	"character_b_role": "중력 화력형", "character_b_shot": "크러시 랜스",
	"character_b_desc": "좁은 사격 범위 / 최대 충격",
	"character_c_role": "위상 기동형", "character_c_shot": "페이즈 팬",
	"character_c_desc": "넓은 공격 범위 / 빠른 이동",
	"vector_suspended": "벡터 일시정지", "pause_sub": "일시정지 // 네온 지구",
	"resume": "계속하기", "restart_stage": "스테이지 재시작", "audio": "오디오: %d%%", "quit_title": "타이틀로 나가기",
	"retry": "다시 도전", "return_title": "타이틀로 돌아가기", "mission_complete": "임무 완료",
	"practice_complete": "연습 완료", "practice_report": "세라프 // 훈련 분석", "practice_report_stage": "%s // 훈련 분석",
	"vector_lost": "벡터 소실", "after_action": "네온 지구 // 전투 결과 보고",
	"combat_score": "전투 점수", "enemies_destroyed": "격파한 적", "graze": "그레이즈",
	"max_chain": "최대 체인", "vector_losses": "잃은 목숨", "barriers_used": "사용한 배리어",
	"clear_time": "클리어 시간", "phase_bonus": "페이즈 보너스", "total_score": "총점",
	"performance_medals": "퍼포먼스 훈장", "medal_bonus": "훈장 보너스",
	"medal_no_miss": "무상 벡터", "medal_no_miss_desc": "목숨을 잃지 않고 작전을 클리어합니다.",
	"medal_no_barrier": "봉인된 무장", "medal_no_barrier_desc": "사이킥 배리어를 한 번도 사용하지 않고 클리어합니다.",
	"medal_phase_perfect": "페이즈 지배자", "medal_phase_perfect_desc": "모든 보스 페이즈를 오버드라이브 전에 격파합니다.",
	"new_high_score": "최고 점수 갱신", "score": "점수", "high_score": "최고 점수",
	"vector": "벡터", "chain": "체인", "phase": "페이즈", "overdrive": "오버드라이브",
	"stage_title": "네온 지구", "stage_sub": "07 구역 // 통제 중추 접근 중",
	"boss_arbiter_name": "아비터-03", "boss_seraph_name": "세라프 집행관",
	"null_tempest_title": "널 템페스트", "null_tempest_subtitle": "붕괴된 공중 도시 // 폭풍 상승로",
	"null_tempest_result": "널 템페스트 // 전투 결과 보고", "null_tempest_pause": "일시정지 // 널 템페스트",
	"boss_ion_warden_name": "이온 워든", "boss_ion_warden_subtitle": "대기권 봉쇄 엔진",
	"boss_ion_warden_defeat_title": "워든 방전 완료", "boss_ion_warden_defeat_subtitle": "상승 통로 복구",
	"boss_void_archon_name": "보이드 아콘", "boss_void_archon_subtitle": "호라이즌급 사이킥 이상체",
	"boss_void_archon_defeat_title": "지평선 붕괴", "boss_void_archon_defeat_subtitle": "폭풍이 걷히고 있습니다",
	"helios_forge_title": "헬리오스 포지", "helios_forge_subtitle": "궤도 주조소 // 이클립스 코어",
	"helios_forge_result": "헬리오스 포지 // 전투 결과 보고", "helios_forge_pause": "일시정지 // 헬리오스 포지",
	"boss_crown_harvester_name": "크라운 하베스터", "boss_crown_harvester_subtitle": "궤도 태양 수확기",
	"boss_crown_harvester_defeat_title": "크라운 해체 완료", "boss_crown_harvester_defeat_subtitle": "이클립스 코어 노출",
	"boss_aurelion_zero_name": "아우렐리온 제로", "boss_aurelion_zero_subtitle": "명령 태양 원형체",
	"boss_aurelion_zero_defeat_title": "거짓 태양 소멸", "boss_aurelion_zero_defeat_subtitle": "명령망 침묵 확인",
	"hostile_surge": "적 증원 감지", "chain_window": "체인 유지 시간 연장",
	"environment_hazard": "환경 위험 감지", "evasive_action": "즉시 회피 기동 필요",
	"final_boss_sub": "사이킥 병기 // 위협 등급 오메가", "midboss_sub": "공중 심판 플랫폼",
	"arbiter_down": "아비터 격파", "advance_spine": "중앙 통제 중추로 진격",
	"control_severed": "통제 중추 절단", "lockdown_collapsing": "도시 봉쇄 붕괴 중",
	"vector_disrupted": "벡터 손상", "life_signal": "잔여 생명 %d", "power_up": "파워 업",
	"warning": "경고", "psychic_signal": "고위 사이킥 신호 감지",
	"signature_confirmed": "사이킥 신호 확인",
	"boss_phase_perimeter": "경계선 봉쇄", "boss_phase_rotary": "회전 심판",
	"boss_phase_arbiter": "아비터 과부하", "boss_phase_sentence": "벡터 선고",
	"boss_phase_halo": "헤일로 엔진", "boss_phase_maelstrom": "시냅스 대소용돌이",
	"boss_phase_lattice": "무의 격자", "boss_phase_last_light": "최후 광휘 프로토콜",
	"boss_phase_static_verdict": "정전기 선고", "boss_phase_ion_shear": "이온 전단",
	"boss_phase_thunder_cage": "뇌전 감옥", "boss_phase_eye_of_storm": "폭풍의 눈",
	"boss_phase_violet_front": "자색 전선", "boss_phase_chain_lightning": "연쇄 번개",
	"boss_phase_broken_sky": "부서진 하늘", "boss_phase_zero_horizon": "제로 호라이즌",
	"boss_phase_reaping_orbit": "수확 궤도", "boss_phase_crown_arc": "크라운 아크",
	"boss_phase_furnace_lock": "용광로 봉쇄", "boss_phase_first_ignition": "최초 점화",
	"boss_phase_photosphere_crown": "광구의 왕관", "boss_phase_prominence_lances": "홍염 창격",
	"boss_phase_blackbody_dominion": "흑체 지배", "boss_phase_last_dawn": "최후 새벽 프로토콜"
}

static func text(key: String) -> String:
	var locale := String(SaveManager.settings.get("language", "en"))
	var catalog: Dictionary = KO if locale == "ko" else EN
	return String(catalog.get(key, EN.get(key, key)))

static func is_korean() -> bool:
	return String(SaveManager.settings.get("language", "en")) == "ko"
