class_name GameText
extends RefCounted

const EN := {
	"start_game": "START GAME", "boss_practice": "BOSS PRACTICE", "combat_archive": "COMBAT ARCHIVE", "options": "OPTIONS", "how_to_play": "HOW TO PLAY", "quit": "QUIT",
	"archive_sub": "LOCAL AFTER-ACTION ANALYTICS // LAST 60 CAMPAIGN RUNS",
	"archive_runs": "RUNS", "archive_clears": "CLEARS", "clear_rate": "CLEAR RATE",
	"average_losses": "AVG LOSSES", "average_barriers": "AVG BARRIERS", "best_clear": "BEST CLEAR",
	"best_score": "BEST SCORE", "overdrive_rate": "OVERDRIVE RATE", "recent_runs": "RECENT RUNS",
	"vector_breakdown": "VECTOR BREAKDOWN",
	"no_run_data": "NO CAMPAIGN DATA FOR THIS DIFFICULTY", "export_data": "EXPORT PLAYTEST JSON",
	"export_success": "JSON SAVED TO THE USER DATA FOLDER", "export_failed": "EXPORT FAILED",
	"archive_back": "BACK TO TITLE", "cleared_short": "CLEAR", "failed_short": "LOST", "assisted_short": "ASSIST",
	"watch_replay": "WATCH LAST REPLAY", "replay_mode": "REPLAY", "replay_sub": "LAST RUN // INPUT PLAYBACK",
	"replay_verified": "REPLAY VERIFIED // RESULTS MATCH", "replay_desync": "REPLAY DESYNC // RESULTS DIFFER",
	"replay_unavailable": "NO COMPATIBLE REPLAY AVAILABLE", "replay_invalid": "REPLAY ENDED // INCOMPLETE OR INCOMPATIBLE DATA",
	"practice_select": "SELECT PRACTICE VECTOR", "practice_sub": "SERAPH EXECUTOR // CHOOSE A START PHASE",
	"practice_phase_hint": "UP / DOWN  START PHASE %02d // %s",
	"difficulty_hint": "UP / DOWN  %s // %s",
	"difficulty_story": "STORY", "difficulty_story_desc": "5 LIVES / 78% THREAT",
	"difficulty_normal": "NORMAL", "difficulty_normal_desc": "3 LIVES / ORIGINAL BALANCE",
	"difficulty_expert": "EXPERT", "difficulty_expert_desc": "2 LIVES / 118% THREAT",
	"briefing_title": "COMBAT BRIEFING",
	"start_training": "PLAY INTERACTIVE TRAINING",
	"training_title": "VECTOR CALIBRATION", "training_sub": "LIVE CONTROL TUTORIAL // INPUTS USE YOUR CURRENT BINDINGS",
	"training_skip": "SKIP TRAINING", "training_deploy": "CALIBRATION COMPLETE",
	"training_move": "01 // MANEUVER", "training_primary": "02 // PRIMARY SHOT",
	"training_focus": "03 // FOCUS ATTACK", "training_barrier": "04 // PSYCHIC BARRIER",
	"training_complete": "VECTOR SYNCHRONIZED",
	"training_move_desc": "%s %s %s %s / ARROWS / LEFT STICK\nTRAVEL THROUGH THE CALIBRATION FIELD",
	"training_primary_desc": "HOLD %s / %s TO FIRE\nWIDE SUSTAINED ATTACK FOR ROUTE ENEMIES",
	"training_focus_desc": "HOLD %s / %s FOR FOCUS\nPRECISE MOVEMENT AND CONCENTRATED DAMAGE",
	"training_barrier_desc": "PRESS %s / %s NOW\nERASE THE ENCLOSING BULLETS",
	"training_complete_desc": "MOVEMENT, ATTACK, AND DEFENSE VERIFIED\nTHE NEON DISTRICT IS READY",
	"training_target": "HOLOGRAPHIC TARGET", "training_progress": "CALIBRATION %03d%%",
	"training_hold": "PERFORM THE HIGHLIGHTED ACTION", "training_complete_hint": "CONFIRM TO CONTINUE TO VECTOR SELECTION",
	"briefing_body": "REACH THE CONTROL SPINE AND DESTROY SERAPH.\n\nPRIMARY SHOT — sustained wide attack\nFOCUS ATTACK — slower precision movement and concentrated fire\nPSYCHIC BARRIER — clears nearby bullets; refills to 3 after a lost life\n\nGRADE 3 — fast straight triple burst\nGRADE 2 — medium-speed radial attack\nGRADE 1 — slow circular attack, fired three times\n\nTHE MIDBOSS PAUSES THE THREE-MINUTE ROUTE CLOCK.\nTHE FINAL BOSS ARRIVES AT 03:00 OF ROUTE TIME.",
	"system_options": "SYSTEM OPTIONS", "master": "MASTER", "music": "MUSIC", "sfx": "SFX",
	"screen_shake": "SCREEN SHAKE", "flash": "FLASH", "bullet_contrast": "BULLET CONTRAST",
	"auto_fire": "AUTO PRIMARY FIRE", "auto_barrier": "AUTO BARRIER INTERCEPT", "show_hitbox": "ALWAYS SHOW HITBOX",
	"fullscreen": "FULLSCREEN", "language": "LANGUAGE: ENGLISH", "accessibility_assists": "ACCESSIBILITY & ASSISTS",
	"assist_preset": "ASSIST PRESET", "assist_standard": "STANDARD", "assist_comfort": "COMFORT", "assist_guardian": "GUARDIAN", "assist_custom": "CUSTOM",
	"assist_standard_desc": "Original presentation and manual defense.",
	"assist_comfort_desc": "Reduced motion and flashes, clear bullets, auto fire, and visible hitbox.",
	"assist_guardian_desc": "Comfort settings plus automatic barrier interception.",
	"assist_custom_desc": "Custom accessibility configuration.",
	"assist_ranking_note": "AUTO BARRIER MARKS THE RUN AS ASSISTED AND DISABLES RECORD SUBMISSION.",
	"assist_active": "ASSIST ACTIVE", "assisted_report": "ASSISTED RUN // RECORD DISABLED",
	"auto_barrier_trigger": "AUTO BARRIER", "auto_barrier_sub": "DAMAGE INTERCEPTED // RECORD DISABLED",
	"key_bindings": "KEY BINDINGS", "back": "BACK", "back_options": "BACK TO OPTIONS",
	"binding_device": "%s BINDINGS", "device_keyboard": "KEYBOARD", "device_gamepad": "GAMEPAD",
	"reset_keys": "RESET DEFAULT KEYS", "reset_gamepad": "RESET GAMEPAD BUTTONS", "press_key": "PRESS A KEY", "press_button": "PRESS A BUTTON",
	"binding_hint": "SELECT AN ACTION, THEN PRESS A KEY\nESC CANCELS // CONTROLLER INPUTS STAY ACTIVE",
	"gamepad_binding_hint": "SELECT AN ACTION, THEN PRESS A GAMEPAD BUTTON\nESC CANCELS // MOVEMENT STAYS ON STICK / D-PAD",
	"gamepad_connected": "%d GAMEPAD CONNECTED", "gamepad_disconnected": "NO GAMEPAD // SETTINGS APPLY ON CONNECTION",
	"controller_connected": "GAMEPAD CONNECTED", "controller_disconnected": "GAMEPAD DISCONNECTED // KEYBOARD ACTIVE",
	"save_recovered": "SAVE RECOVERED // LAST VALID BACKUP RESTORED",
	"controls_hint": "MOVE  %s / ARROWS / STICK\nSHOT  %s / %s   FOCUS  %s / %s\nBARRIER  %s / %s   PAUSE  ESC / START",
	"move_up": "MOVE UP", "move_down": "MOVE DOWN", "move_left": "MOVE LEFT", "move_right": "MOVE RIGHT",
	"primary": "PRIMARY SHOT", "focus": "FOCUS ATTACK", "barrier": "PSYCHIC BARRIER",
	"select_vector": "SELECT YOUR VECTOR", "select_sub": "ESCAPED SUBJECT // COMBAT LOADOUT",
	"focus_desc": "FOCUS: precision movement + concentrated psychic channel",
	"select": "SELECT", "deploy": "DEPLOY", "speed": "SPEED", "power": "POWER", "width": "WIDTH",
	"character_a_role": "VECTOR BALANCE", "character_a_shot": "TRI-VECTOR",
	"character_a_desc": "Stable spread / adaptive focus",
	"character_b_role": "GRAVITY POWER", "character_b_shot": "CRUSH LANCE",
	"character_b_desc": "Narrow field / maximum impact",
	"character_c_role": "PHASE SPEED", "character_c_shot": "PHASE FAN",
	"character_c_desc": "Wide coverage / rapid movement",
	"vector_suspended": "VECTOR SUSPENDED", "pause_sub": "PAUSE // NEON DISTRICT",
	"resume": "RESUME", "restart_stage": "RESTART STAGE", "audio": "AUDIO: %d%%", "quit_title": "QUIT TO TITLE",
	"retry": "RETRY", "return_title": "RETURN TO TITLE", "mission_complete": "MISSION COMPLETE",
	"practice_complete": "PRACTICE COMPLETE", "practice_report": "SERAPH // TRAINING ANALYSIS",
	"vector_lost": "VECTOR LOST", "after_action": "NEON DISTRICT // AFTER-ACTION REPORT",
	"combat_score": "COMBAT SCORE", "enemies_destroyed": "ENEMIES DESTROYED", "graze": "GRAZE",
	"max_chain": "MAX CHAIN", "vector_losses": "VECTOR LOSSES", "barriers_used": "BARRIERS USED",
	"clear_time": "CLEAR TIME", "phase_bonus": "PHASE BONUS", "total_score": "TOTAL SCORE",
	"new_high_score": "NEW HIGH SCORE", "score": "SCORE", "high_score": "HIGH SCORE",
	"vector": "VECTOR", "chain": "CHAIN", "phase": "PHASE", "overdrive": "OVERDRIVE",
	"stage_title": "NEON DISTRICT", "stage_sub": "SECTOR 07 // CONTROL SPINE APPROACH",
	"hostile_surge": "HOSTILE SURGE", "chain_window": "CHAIN WINDOW EXTENDED",
	"final_boss_sub": "PSYCHIC WEAPON // THREAT OMEGA", "midboss_sub": "AERIAL VERDICT PLATFORM",
	"arbiter_down": "ARBITER DOWN", "advance_spine": "ADVANCE TO CENTRAL SPINE",
	"control_severed": "CONTROL SPINE SEVERED", "lockdown_collapsing": "CITY LOCKDOWN COLLAPSING",
	"vector_disrupted": "VECTOR DISRUPTED", "life_signal": "LIFE SIGNAL %d", "power_up": "POWER UP",
	"warning": "WARNING", "psychic_signal": "HIGH-ORDER PSYCHIC SIGNAL",
	"signature_confirmed": "PSYCHIC SIGNATURE CONFIRMED",
	"boss_phase_perimeter": "PERIMETER DENIAL", "boss_phase_rotary": "ROTARY JUDGEMENT",
	"boss_phase_arbiter": "ARBITER OVERDRIVE", "boss_phase_sentence": "VECTOR SENTENCE",
	"boss_phase_halo": "HALO ENGINE", "boss_phase_maelstrom": "SYNAPTIC MAELSTROM",
	"boss_phase_lattice": "LATTICE OF NULL", "boss_phase_last_light": "LAST LIGHT PROTOCOL"
}

const KO := {
	"start_game": "게임 시작", "boss_practice": "보스 연습", "combat_archive": "전투 기록", "options": "옵션", "how_to_play": "플레이 방법", "quit": "종료",
	"archive_sub": "로컬 전투 분석 // 최근 캠페인 60회",
	"archive_runs": "플레이", "archive_clears": "클리어", "clear_rate": "클리어율",
	"average_losses": "평균 손실", "average_barriers": "평균 배리어", "best_clear": "최고 클리어",
	"best_score": "최고 점수", "overdrive_rate": "오버드라이브율", "recent_runs": "최근 플레이",
	"vector_breakdown": "벡터별 분석",
	"no_run_data": "이 난이도의 캠페인 기록이 없습니다", "export_data": "플레이테스트 JSON 내보내기",
	"export_success": "JSON을 사용자 데이터 폴더에 저장했습니다", "export_failed": "내보내기 실패",
	"archive_back": "타이틀로", "cleared_short": "클리어", "failed_short": "실패", "assisted_short": "어시스트",
	"watch_replay": "마지막 플레이 리플레이", "replay_mode": "리플레이", "replay_sub": "마지막 플레이 // 입력 재생",
	"replay_verified": "리플레이 검증 완료 // 결과 일치", "replay_desync": "리플레이 불일치 // 결과 차이",
	"replay_unavailable": "재생 가능한 리플레이가 없습니다", "replay_invalid": "리플레이 종료 // 불완전하거나 호환되지 않는 데이터",
	"practice_select": "연습용 벡터 선택", "practice_sub": "세라프 집행자 // 시작 페이즈 선택",
	"practice_phase_hint": "위 / 아래  시작 페이즈 %02d // %s",
	"difficulty_hint": "위 / 아래  %s // %s",
	"difficulty_story": "스토리", "difficulty_story_desc": "목숨 5 / 위협도 78%",
	"difficulty_normal": "노멀", "difficulty_normal_desc": "목숨 3 / 기존 밸런스",
	"difficulty_expert": "익스퍼트", "difficulty_expert_desc": "목숨 2 / 위협도 118%",
	"briefing_title": "전투 브리핑",
	"start_training": "실전 조작 훈련",
	"training_title": "벡터 동기화 훈련", "training_sub": "실전 조작 튜토리얼 // 현재 키 설정 사용",
	"training_skip": "훈련 건너뛰기", "training_deploy": "동기화 완료",
	"training_move": "01 // 기동", "training_primary": "02 // 약공격",
	"training_focus": "03 // 강공격", "training_barrier": "04 // 사이킥 배리어",
	"training_complete": "벡터 동기화 완료",
	"training_move_desc": "%s %s %s %s / 방향키 / 왼쪽 스틱\n훈련 공간을 이동하세요",
	"training_primary_desc": "%s / %s 눌러 발사\n일반 적을 위한 넓은 지속 공격",
	"training_focus_desc": "%s / %s 눌러 집중\n정밀 이동과 집중 화력",
	"training_barrier_desc": "%s / %s 지금 입력\n주변을 조여오는 탄환을 제거하세요",
	"training_complete_desc": "이동·공격·방어 검증 완료\n네온 지구 출격 준비 완료",
	"training_target": "홀로그램 표적", "training_progress": "동기화 %03d%%",
	"training_hold": "표시된 동작을 수행하세요", "training_complete_hint": "확인하면 벡터 선택으로 이동합니다",
	"briefing_body": "통제 중추에 도달해 세라프를 파괴하십시오.\n\n약공격 — 넓은 범위를 지속 공격\n강공격 — 느린 정밀 이동과 집중 사격\n사이킥 배리어 — 주변 탄환 제거, 목숨을 잃으면 3개로 충전\n\n3등급 — 빠른 직선 3점사\n2등급 — 중속 방사형 공격\n1등급 — 느린 원형 공격을 3회 연속 발사\n\n중간보스 전투 중에는 3분 경로 타이머가 멈춥니다.\n최종 보스는 경로 시간 03:00에 등장합니다.",
	"system_options": "시스템 옵션", "master": "전체 음량", "music": "음악", "sfx": "효과음",
	"screen_shake": "화면 흔들림", "flash": "섬광 효과", "bullet_contrast": "적탄 대비",
	"auto_fire": "약공격 자동 발사", "auto_barrier": "배리어 자동 방어", "show_hitbox": "피격점 항상 표시",
	"fullscreen": "전체 화면", "language": "언어: 한국어", "accessibility_assists": "접근성 및 어시스트",
	"assist_preset": "어시스트 프리셋", "assist_standard": "표준", "assist_comfort": "컴포트", "assist_guardian": "가디언", "assist_custom": "사용자 설정",
	"assist_standard_desc": "기존 연출과 수동 방어를 사용합니다.",
	"assist_comfort_desc": "흔들림과 섬광을 줄이고 적탄·자동 사격·피격점 표시를 강화합니다.",
	"assist_guardian_desc": "컴포트 설정에 배리어 자동 방어를 추가합니다.",
	"assist_custom_desc": "사용자가 조정한 접근성 설정입니다.",
	"assist_ranking_note": "배리어 자동 방어를 사용하면 어시스트 플레이로 표시되며 기록이 등록되지 않습니다.",
	"assist_active": "어시스트 활성", "assisted_report": "어시스트 플레이 // 기록 등록 안 됨",
	"auto_barrier_trigger": "배리어 자동 방어", "auto_barrier_sub": "피격 차단 // 기록 등록 안 됨",
	"key_bindings": "키 설정", "back": "뒤로", "back_options": "옵션으로 돌아가기",
	"binding_device": "%s 설정", "device_keyboard": "키보드", "device_gamepad": "게임패드",
	"reset_keys": "기본 키로 초기화", "reset_gamepad": "게임패드 버튼 초기화", "press_key": "키를 입력하세요", "press_button": "버튼을 입력하세요",
	"binding_hint": "동작을 선택한 뒤 키를 누르세요\nESC 취소 // 컨트롤러 입력은 유지됩니다",
	"gamepad_binding_hint": "동작을 선택한 뒤 게임패드 버튼을 누르세요\nESC 취소 // 이동은 스틱과 방향 패드 유지",
	"gamepad_connected": "게임패드 %d개 연결됨", "gamepad_disconnected": "게임패드 없음 // 연결 시 설정 적용",
	"controller_connected": "게임패드 연결됨", "controller_disconnected": "게임패드 연결 해제 // 키보드 사용 가능",
	"save_recovered": "저장 데이터 복구 // 마지막 정상 백업 복원",
	"controls_hint": "이동  %s / 방향키 / 스틱\n약공격  %s / %s   강공격  %s / %s\n배리어  %s / %s   일시정지  ESC / START",
	"move_up": "위로 이동", "move_down": "아래로 이동", "move_left": "왼쪽 이동", "move_right": "오른쪽 이동",
	"primary": "약공격", "focus": "강공격", "barrier": "사이킥 배리어",
	"select_vector": "벡터 선택", "select_sub": "탈주 실험체 // 전투 장비",
	"focus_desc": "집중: 정밀 이동 + 사이킥 집중 사격",
	"select": "선택", "deploy": "출격", "speed": "속도", "power": "화력", "width": "범위",
	"character_a_role": "균형형 벡터", "character_a_shot": "트라이 벡터",
	"character_a_desc": "안정적인 확산 / 적응형 집중",
	"character_b_role": "중력 화력형", "character_b_shot": "크러시 랜스",
	"character_b_desc": "좁은 사격 범위 / 최대 충격",
	"character_c_role": "위상 기동형", "character_c_shot": "페이즈 팬",
	"character_c_desc": "넓은 공격 범위 / 빠른 이동",
	"vector_suspended": "벡터 일시정지", "pause_sub": "일시정지 // 네온 지구",
	"resume": "계속하기", "restart_stage": "스테이지 재시작", "audio": "오디오: %d%%", "quit_title": "타이틀로 나가기",
	"retry": "다시 도전", "return_title": "타이틀로 돌아가기", "mission_complete": "임무 완료",
	"practice_complete": "연습 완료", "practice_report": "세라프 // 훈련 분석",
	"vector_lost": "벡터 소실", "after_action": "네온 지구 // 전투 결과 보고",
	"combat_score": "전투 점수", "enemies_destroyed": "격파한 적", "graze": "그레이즈",
	"max_chain": "최대 체인", "vector_losses": "잃은 목숨", "barriers_used": "사용한 배리어",
	"clear_time": "클리어 시간", "phase_bonus": "페이즈 보너스", "total_score": "총점",
	"new_high_score": "최고 점수 갱신", "score": "점수", "high_score": "최고 점수",
	"vector": "벡터", "chain": "체인", "phase": "페이즈", "overdrive": "오버드라이브",
	"stage_title": "네온 지구", "stage_sub": "07 구역 // 통제 중추 접근 중",
	"hostile_surge": "적 증원 감지", "chain_window": "체인 유지 시간 연장",
	"final_boss_sub": "사이킥 병기 // 위협 등급 오메가", "midboss_sub": "공중 심판 플랫폼",
	"arbiter_down": "아비터 격파", "advance_spine": "중앙 통제 중추로 진격",
	"control_severed": "통제 중추 절단", "lockdown_collapsing": "도시 봉쇄 붕괴 중",
	"vector_disrupted": "벡터 손상", "life_signal": "잔여 생명 %d", "power_up": "파워 업",
	"warning": "경고", "psychic_signal": "고위 사이킥 신호 감지",
	"signature_confirmed": "사이킥 신호 확인",
	"boss_phase_perimeter": "경계선 봉쇄", "boss_phase_rotary": "회전 심판",
	"boss_phase_arbiter": "아비터 과부하", "boss_phase_sentence": "벡터 선고",
	"boss_phase_halo": "헤일로 엔진", "boss_phase_maelstrom": "시냅스 대소용돌이",
	"boss_phase_lattice": "무의 격자", "boss_phase_last_light": "최후 광휘 프로토콜"
}

static func text(key: String) -> String:
	var locale := String(SaveManager.settings.get("language", "en"))
	var catalog: Dictionary = KO if locale == "ko" else EN
	return String(catalog.get(key, EN.get(key, key)))

static func is_korean() -> bool:
	return String(SaveManager.settings.get("language", "en")) == "ko"
